# Generated by Django 5.1.1 on 2026-08-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок"
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="Место"),
                ),
                (
                    "category",
                    models.CharField(
                        default="Разное", max_length=50, verbose_name="Категория"
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
