# Generated by Django 5.1.1 on 2026-08-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_category_alter_post_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="title",
        ),
    ]
