# Generated by Django 5.1.1 on 2026-08-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date",
            field=models.CharField(
                default="Не указана",
                help_text="Например: 30 сентября 1659 года",
                max_length=100,
                verbose_name="Дата",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="location",
            field=models.CharField(
                default="Не указана",
                help_text="Например: Остров отчаянья",
                max_length=200,
                verbose_name="Место",
            ),
            preserve_default=False,
        ),
    ]
