# Generated by Django 5.1.1 on 2026-08-05 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_name_category_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="text",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.RemoveField(
            model_name="post",
            name="date",
        ),
        migrations.RemoveField(
            model_name="post",
            name="location",
        ),
        migrations.AddField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
