# Generated by Django 5.1.1 on 2026-08-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                help_text="Введите заголовок поста, он должен быть уникальным и понятным для читателя",
                max_length=200,
            ),
        ),
    ]
