# Generated by Django 5.1.1 on 2026-08-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
