# Generated by Django 5.1.1 on 2026-08-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_date_alter_post_location_alter_post_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="title",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="post",
            name="location",
            field=models.CharField(
                help_text="Например: Остров отчаянья",
                max_length=200,
                verbose_name="Место",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                help_text="Введите заголовок поста, он должен быть уникальным и понятным для читателя",
                max_length=200,
            ),
        ),
    ]
