# Generated by Django 5.1.1 on 2026-08-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_rename_title_category_name_alter_post_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="published_at",
        ),
    ]
