# Generated by Django 5.1.1 on 2026-08-20 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_post_pub_date_post_text_alter_post_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.date(2026, 8, 20)
            ),
            preserve_default=False,
        ),
    ]
